function bwplot(x, y, size_x, size_y, label_x, label_y, legends, location)
% usual sizes: 15x4, 15x5, 15x7.5 e 7x7 (cm)

% create figure with the desired size
figure('Units'             , 'centimeters', ...
       'PaperUnits'        , 'centimeters', ...
       'Position'          , [2 5 size_x size_y],...
       'PaperPositionMode' , 'auto');
set(gcf, 'Color', 'w')

s_x = size(x);

% plot configuration
line_color = [0 0 0; 0.5 0.5 0.5; 0.7 0.7 0.7; 0.75 0.75 0.75];
marker_type = {'none', 's', 'o', 'p'};
n_mk = [1, 10, 8, 12];
m_size = [1, 70, 70, 100];
m_size_l = [1, 8, 8, 10];
line_style = {'-', '--', '-.', ':'};

for i = 1:s_x(2)
    cfg = rem(length(line_color)-1+i, length(line_color)) + 1;
    plot_line = line(x(:,i), y(:,i));
    set(plot_line, 'LineWidth', 1.5, ...
        'Color', line_color(cfg, :), ...
        'LineStyle', line_style{cfg});
    hold on
    % plot markers
    line_m = scatter(x(int64(1+end/n_mk(cfg)):int64(end/n_mk(cfg)):end, i), ...  
                    y(int64(1+end/n_mk(cfg)):int64(end/n_mk(cfg)):end, i), m_size(cfg));
    set(line_m, 'MarkerEdgeColor', line_color(cfg, :), ...
                 'MarkerFaceColor', [1, 1, 1], ...
                 'Marker', marker_type{cfg}, ...
                 'LineWidth', 1.5);
    % plot for legend
    line_l(i) = line(x(1, i), y(1, i));
    set(line_l(i), 'LineWidth', 1.5, ...
                   'Color', line_color(cfg, :), ...
                   'LineStyle', line_style{cfg}, ...
                   'MarkerEdgeColor', line_color(cfg, :), ...
                   'MarkerFaceColor', [1, 1, 1], ...
                   'Marker', 's', ...
                   'MarkerSize', m_size_l(cfg),...
                   'LineWidth', 1.5);
end
xmin = min(min(x));
xmax = max(max(x));
ymin = min(min(y));
ymax = max(max(y));


% setup the plot style
y_extra = 0.03;
if ymin <= 0 && ymax <= 0
    ylims = [ymin*(1+y_extra) ymax*(1-y_extra)];
elseif ymin <= 0 && ymax >= 0
    ylims = [ymin*(1+y_extra) ymax*(1+y_extra)];
else
    ylims = [ymin*(1-y_extra) ymax*(1+y_extra)];
end
xlim([xmin xmax])
ylim(ylims)

fontsize = 12;
set(gca,...
    'Box'           , 'off'     , ...
    'TickDir'       , 'out'     , ...
    'TickLength'    , [.02 .02] , ...
    'XMinorTick'    , 'on'      , ... 
    'YMinorTick'    , 'on'      , ...
    'YGrid'         , 'on'      , ...
    'XGrid'         , 'on'      , ...
    'XColor'        , [.0 .0 .0], ...
    'YColor'        , [.0 .0 .0], ...
    'LineWidth'     , 1, ...
    'Units'         , 'normalized',...
    'FontUnits'     , 'points',...
    'FontWeight'    , 'normal',...
    'FontSize'      , fontsize,...
    'TickLabelInterpreter', 'latex')

ylabel({label_y},...
    'FontUnits', 'points',...
    'interpreter', 'latex',...
    'FontSize', fontsize)
xlabel({label_x},...
    'FontUnits', 'points',...
    'FontWeight', 'normal',...
    'interpreter', 'latex',...
    'FontSize', fontsize)

% if location not defined, consider it Best
try
    location;
catch
    location = 'Best';
end
try
    legend(line_l, legends,...
           'FontUnits', 'points',...
           'Interpreter', 'latex',...
           'FontSize', fontsize,...
           'Location', location)
catch 
end
